import type { Metadata } from "next";
import "./globals.css";
import "../styles/reset.css";
import localFont from "next/font/local";
import Header from "@/components/Header";
import Providers from "@/components/Provider";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const pretendard = localFont({
  src: "../public/fonts/PretendardVariable.woff2",
  display: "swap",
  weight: "45 920",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={pretendard.className}>
        <Providers>
          <div className="wrapper">
            <Header />
            <div className="contentWrapper">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
